services:
  frontend:
    container_name: convex-frontend
    env_file:
      - ./.env.local
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - convex-network

  nginx:
    container_name: convex-nginx
    build:
      context: nginx
    restart: always
    tty: true
    ports:
      - "80:80"
    networks:
      - convex-network
    depends_on:
      - frontend

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  convex-network:
    external: true
